### ISSUE TITLE
`cmip_urls()` only gets one URL per result?

### ISSUE THREAD

**Issue by eliocamp** [eliocamp/rcmip6#12]
@mdsumner I'm refactoring the code here and there to use `curl::download_multi()` for concurrent downloads and I noticed that the `cmip_urls()` function only returns one URL per result. However, some results are split into multiple files. Is this function only returning the first one? 

https://github.com/eliocamp/rcmip6/blob/c04bbcec81177899d3cc90df5949c0984d05912e/R/cmip-urls.R#L32

I'm changing this to return a list of length equal to `nrow(results)` with a vector of urls. Do you think it's reasonable?

**Comment by mdsumner** [comment]
oh sounds good, I think ai hadn't seen a case of multiple 🙏
